
stages:
  - prepare
  - test
  - build
  - deploy

image: node:8

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ./node_modules/

install:
  stage: prepare
  tags:
    - docker
  script:
    - yarn

lint:
  stage: test
  tags:
    - docker
  before_script:
    - yarn install
  script:
    - yarn lint
  allow_failure: true

lint-critical:
  stage: test
  tags:
    - docker
  before_script:
    - yarn install
  script:
    - yarn lint:critical
  # allow_failure: true

test:
  stage: test
  tags:
    - docker
  before_script:
    - yarn install
  script:
    - yarn test
  allow_failure: true

build:
  stage: build
  tags:
    - docker
  script:
    - export CI=
    - yarn build
  artifacts:
    paths:
      - ./build/

deploy:
  stage: deploy
  dependencies:
    - build
  tags:
    - docker
  image: emiketic/essentials
  only:
    - master
  script:
    - ./scripts/upload.sh ./build/
